spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/librarydb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:library}
spring.datasource.password=${DB_PASSWORD:library}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
